package dk.medtrace.autogenerated.datamodel;


/**
 * AUTOGENERATED. Do not modify beyond this point.
 */

import lombok.Data;

import java.time.LocalDate;

@Data
public class ToDoItem {
    LocalDate dueDate;
    String description;
    boolean completed;
}
