package dk.medtrace.autogenerated.enums;

/**
 * Autogenerated: Do not modify beyond this point.
 */
public enum Priority {
    URGENT("textkey.urgent"),
    NORMAL("textkey.normal"),
    WHENEVER("textkey.whenever");

    final String description;

    Priority(String description) {
        this.description = description;
    }
}
