package dk.medtrace.repository;

import dk.medtrace.autogenerated.datamodel.ToDoItem;

import java.util.List;

public interface ToDoRepository {

    public List<ToDoItem> getToDoList();

    public boolean saveToDoList(List<ToDoItem> toDoItemList);
}
